[cookie]
name = "traffic_grapher_auth"
key = "some_random_signing_key_change_this"
expiry_days = 30

[credentials.usernames.jsmith]
email = "jsmith@company.com"
name = "John Smith"
password = "SomePlainTextPassword"
