[cookie]
name = "traffic_grapher_auth"
key = "cbc675525385b29de465a6fc516901a9c6fa4b82a96918519485434cea8daaec"
expiry_days = 30

[credentials.usernames.jsmith]
email = "jsmith@company.com"
name = "John Smith"
password = "admin1234"
